// Home page of the app.
// Currently a placeholder "building" screen shown while the app is generated.
// Replace this file with your actual app UI. Do not delete it to use some other file as homepage. Simply replace the entire contents of this file.

import Head from "next/head";
import { motion } from "framer-motion";

const PLACEHOLDER_CSS = `
  .lv-placeholder {
    --lv-bg: #ffffff;
    --lv-text: #0d0f11;
    --lv-muted: rgba(13, 15, 17, 0.58);
    --lv-faint: rgba(13, 15, 17, 0.38);
    --lv-line: rgba(13, 15, 17, 0.1);
  }
  @media (prefers-color-scheme: dark) {
    .lv-placeholder {
      --lv-bg: #08090a;
      --lv-text: #f5f5f4;
      --lv-muted: rgba(245, 245, 244, 0.62);
      --lv-faint: rgba(245, 245, 244, 0.34);
      --lv-line: rgba(245, 245, 244, 0.12);
    }
  }
  @keyframes lv-spin {
    to { transform: rotate(360deg); }
  }
  .lv-spinner {
    width: 1.5rem;
    height: 1.5rem;
    border: 2px solid var(--lv-line);
    border-top-color: var(--lv-text);
    border-radius: 9999px;
    animation: lv-spin 0.8s linear infinite;
  }
  @media (prefers-reduced-motion: reduce) {
    .lv-spinner {
      animation: none;
    }
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Building your app - Lumaveno</title>
        <meta name="description" content="Your application is being generated by Lumaveno." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="lv-placeholder min-h-screen flex flex-col items-center justify-center p-6 overflow-hidden relative"
        style={{ background: "var(--lv-bg)", color: "var(--lv-text)" }}
      >
        <style>{PLACEHOLDER_CSS}</style>

        <header className="absolute top-8 left-1/2 -translate-x-1/2 flex items-center gap-2 select-none">
          {/* Lumaveno mark - inherits the theme color via currentColor */}
          <svg viewBox="0 0 32 32" fill="currentColor" fillRule="evenodd" role="img" aria-label="Lumaveno" className="w-5 h-5">
            <path d="M8.5 3 H23.5 A5.5 5.5 0 0 1 29 8.5 V23.5 A5.5 5.5 0 0 1 23.5 29 H8.5 A5.5 5.5 0 0 1 3 23.5 V8.5 A5.5 5.5 0 0 1 8.5 3 Z M13 9.3 V19.6 A2.4 2.4 0 0 0 15.4 22 H21.7 V18.7 H16.3 V9.3 Z M12.4 22.6 L15.2 19.8 V22 L14.6 22.6 Z" />
          </svg>
          <span className="text-sm font-semibold tracking-tight">Lumaveno</span>
        </header>

        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: "easeOut" }}
          className="text-center space-y-8 relative z-10"
        >
          <div className="space-y-4">
            <h1 className="text-4xl md:text-6xl font-display font-semibold text-balance leading-tight">
              Building your app.
            </h1>
            <p
              className="text-base md:text-lg max-w-md mx-auto text-pretty"
              style={{ color: "var(--lv-muted)" }}
            >
              The first version is being written right now. This preview
              updates on its own — no need to reload.
            </p>
          </div>

          <div className="lv-spinner mx-auto" role="status" aria-label="Building your app" />
        </motion.div>

        <footer
          className="absolute bottom-8 text-center text-sm"
          style={{ color: "var(--lv-faint)" }}
        >
          <p>Powered by Lumaveno</p>
        </footer>
      </main>
    </>
  );
}
